"""
localization.py - runtime translations for visible Qt text.
"""
from PySide6.QtWidgets import QAbstractButton, QComboBox, QGroupBox, QLabel, QLineEdit, QTableWidget, QTabWidget


EN = {
    "Настройки сохранены": "Settings saved",
    "Люкс графит": "Lux Graphite",
    "Люкс ночная": "Lux Midnight",
    "Люкс светлая": "Lux Silver",
    "Лучшее": "Best",
    "Оригинал": "Original",
    "h264 (рекомендуется)": "H.264 (recommended)",
    "Видео": "Video",
    "Только аудио": "Audio only",
    "Картинки/миниатюры": "Images/thumbnails",
    "Документы/описания": "Documents/descriptions",
    "Авто: видеокарта, потом процессор": "Auto: GPU, then CPU",
    "Только видеокарта": "GPU only",
    "Только процессор": "CPU only",
    "Авто": "Auto",
    "Безлимитно": "Unlimited",
    "1 загрузка": "1 download",
    "2 загрузки": "2 downloads",
    "3 загрузки": "3 downloads",
    "4 загрузки": "4 downloads",
    "5 загрузки": "5 downloads",
    "6 загрузки": "6 downloads",
    "7 загрузки": "7 downloads",
    "8 загрузки": "8 downloads",
    "9 загрузки": "9 downloads",
    "10 загрузки": "10 downloads",
    "(не использовать)": "(do not use)",
    "необязательно": "optional",
    "Папка для загрузки": "Download folder",
    "Путь к файлу доступа, если нужен ручной режим": "Access file path for manual mode",
    "Проверка обновлений использует GitHub Releases после настройки репозитория.": "Update checks use GitHub Releases after the repository is configured.",
    "Проверить обновление приложения": "Check app update",
    "Проверка подберет рекомендуемое количество загрузок.": "The check will recommend the best number of concurrent downloads.",
    "Автоматически раскладывать загрузки по сервисам и типам": "Automatically sort downloads by service and type",
    "Переходить в фоновый режим при закрытии окна": "Move to background mode when closing the window",
    "Открывать приложение при запуске Windows": "Open the app when Windows starts",
    "Автоматически проверять обновления приложения": "Automatically check for app updates",
    "Автоматически загружать обновления": "Automatically download updates",
    "Устанавливать бета-версии": "Install beta versions",
    "Автоматически менять кодек после скачивания, если выбран не оригинал": "Automatically change codec after download when Original is not selected",
    "Спрашивать перед сменой кодека": "Ask before changing codec",
    "Сохранять оригиналы после конвертации": "Keep originals after conversion",
    "Показывать AV1 и VP9": "Show AV1 and VP9",
    "Плейлисты, каналы и результаты поиска": "Playlists, channels and search results",
    "Создавать подпапки для плейлистов, каналов и результатов поиска": "Create subfolders for playlists, channels and search results",
    "Нумеровать файлы": "Number files",
    "Пропускать уже скачанные элементы": "Skip already downloaded items",
    "Создавать файл .m3u": "Create .m3u file",
    "Встраивать субтитры, если доступны": "Embed subtitles when available",
    "Удалять завершённые элементы из списка": "Remove completed items from the list",
    "Защита от одинаковых названий файлов": "Protect against duplicate file names",
    "Предлагать скачать канал после нескольких видео с него": "Suggest downloading a channel after several videos from it",
    "Использовать прокси": "Use proxy",
    "Предотвращать сон до завершения загрузок": "Prevent sleep until downloads finish",
    "Показывать уведомление о завершении загрузки": "Show notification when download finishes",
    "Показывать уведомление о завершении обработки": "Show notification when processing finishes",
    "Напоминать скачать новый контент": "Remind about downloading new content",
    "Показывать похожие видео и рекомендации": "Show similar videos and recommendations",
    "Запрашивать подтверждение при активных загрузках": "Ask for confirmation when downloads are active",
    "Показывать в центре уведомлений": "Show in notification center",
    "Проигрывать звук оповещений": "Play notification sound",
    "Автоматически обновлять доступ, когда сайт требует вход": "Automatically refresh access when a site requires sign-in",
    "Отправлять статистику скачиваний": "Send download statistics",
    "Показывать инструменты обработки": "Show processing tools",
    "Автоматически проверять обновления системы загрузки": "Automatically check download-system updates",
    "Создать отчёт:": "Create report:",
    "Скопировать:": "Copy:",
    "Сохранить TXT:": "Save TXT:",
    "Последний лог:": "Latest log:",
    "Последние ошибки:": "Recent errors:",
    "Экспорт:": "Export:",
    "Проверка скорости:": "Speed test:",
    "Повторы:": "Retries:",
    "Браузер:": "Browser:",
    "Профиль:": "Profile:",
    "Кодеки:": "Codecs:",
    "GPU/CPU:": "GPU/CPU:",
    "Конвертация:": "Conversion:",
    "Место:": "Disk space:",
    "Права:": "Permissions:",
    "Временные файлы:": "Temporary files:",
    "Собирает версию приложения, Windows, настройки без личных данных и последние ошибки.": "Collects app version, Windows version, privacy-safe settings and recent errors.",
    "Копирует текст для отправки разработчику.": "Copies text to send to the developer.",
    "Создаёт файл отчёта, который пользователь сам отправляет в поддержку.": "Creates a report file that the user can send to support.",
    "Готов к загрузке": "Ready to download",
    "Диск: —": "Disk: -",
    "Загрузка": "Download",
    "Настройки": "Settings",
    "История": "History",
    "Аккаунты": "Accounts",
    "Исправления": "Fixes",
    "GitHub": "GitHub",
    "Отчёт исправлений": "Fix Report",
    "Загрузка видео, музыки и плейлистов": "Download videos, music and playlists",
    "Поддержка видео, музыки, плейлистов, каналов и клипов": "Supports videos, music, playlists, channels and clips",
    "Вставить ссылку": "Paste link",
    "Скачать": "Download",
    "Проверить": "Check",
    "Профиль загрузки": "Download profile",
    "Качество": "Quality",
    "Контейнер": "Container",
    "Энкодер": "Encoder",
    "Кодек": "Codec",
    "Папка:": "Folder:",
    "Изменить": "Change",
    "Открыть": "Open",
    "Очистить": "Clear",
    "Очередь загрузок": "Download queue",
    "Проверка ссылки покажет сервис, тип, качество, FPS и субтитры.": "Link check shows service, type, quality, FPS and subtitles.",
    "Вставьте ссылку на видео, аудио, плейлист, канал или клип...": "Paste a video, audio, playlist, channel or clip link...",
    "Основные": "General",
    "Формат": "Format",
    "Плейлисты": "Playlists",
    "Соединение": "Connection",
    "Уведомления": "Notifications",
    "Доступ": "Access",
    "Разработчик": "Developer",
    "Сохранить": "Save",
    "Приложение": "Application",
    "Папка": "Folder",
    "Обзор": "Browse",
    "Тема:": "Theme:",
    "Язык:": "Language:",
    "Обновления:": "Updates:",
    "Тип:": "Type:",
    "Качество:": "Quality:",
    "Кадры:": "Frame rate:",
    "Контейнер:": "Container:",
    "Кодек:": "Codec:",
    "Режим:": "Mode:",
    "Энкодер:": "Encoder:",
    "Доступно:": "Available:",
    "Скорость и сеть": "Speed and network",
    "Одновременно:": "Concurrent:",
    "Лимит:": "Limit:",
    "Сеть:": "Network:",
    "Проверить скорость": "Check speed",
    "Прокси:": "Proxy:",
    "Тип": "Type",
    "Сервер:": "Server:",
    "Порт:": "Port:",
    "Логин:": "Username:",
    "Пароль:": "Password:",
    "Аккаунты и доступ": "Accounts and access",
    "Браузер вручную:": "Manual browser:",
    "Файл:": "File:",
    "Режим разработчика": "Developer mode",
    "Показывать расширенную диагностику, логи и технические параметры": "Show extended diagnostics, logs and technical options",
    "Диагностика": "Diagnostics",
    "Логи": "Logs",
    "Сеть": "Network",
    "Видео": "Video",
    "Файлы": "Files",
    "Эксперименты": "Experiments",
    "Support-пакет": "Support package",
    "Инструменты": "Tools",
    "Система загрузки": "Download system",
    "Файл релиза:": "Release file:",
    "Обновить": "Update",
    "Система загрузки готова к работе.": "Download system is ready.",
    "Ошибка загрузки": "Download error",
    "Скопировать отчет": "Copy report",
    "Открыть GitHub": "Open GitHub",
    "История загрузок": "Download history",
    "Локальная история хранится в AppData и не попадает в GitHub.": "Local history is stored in AppData and is never published to GitHub.",
    "Дата": "Date",
    "Источник": "Source",
    "Название": "Title",
    "Размер": "Size",
    "Статус": "Status",
    "Прогресс": "Progress",
    "Скорость": "Speed",
    "ETA": "ETA",
    "Действия": "Actions",
    "Ожидание": "Waiting",
    "Получение информации...": "Reading info...",
    "Загрузка...": "Downloading...",
    "Обработка...": "Processing...",
    "Конвертация...": "Converting...",
    "Пауза": "Paused",
    "Завершено": "Completed",
    "Отменено": "Canceled",
    "Ошибка": "Error",
    "Проверено": "Checked",
    "Готово": "Done",
    "Активно, данные доступа:": "Active, access data:",
    "Не подключено": "Not connected",
    "Проверка...": "Checking...",
    "Войти": "Sign in",
    "Выйти": "Sign out",
    "Контрольная проверка: большой YouTube-плейлист, переданный пользователем 2026-07-28.": "Control test: large YouTube playlist provided by the user on 2026-07-28.",
    "Версия 0.1.1 · дата фикса: 2026-07-28": "Version 0.1.1 · fix date: 2026-07-28",
    "Критично": "Critical",
    "Серьёзно": "Major",
    "Средне": "Medium",
    "Инфо": "Info",
}


DE = EN | {
    "Настройки сохранены": "Einstellungen gespeichert",
    "Люкс графит": "Lux Graphit",
    "Люкс ночная": "Lux Nacht",
    "Люкс светлая": "Lux Hell",
    "Лучшее": "Beste",
    "Оригинал": "Original",
    "h264 (рекомендуется)": "H.264 (empfohlen)",
    "Видео": "Video",
    "Только аудио": "Nur Audio",
    "Картинки/миниатюры": "Bilder/Vorschaubilder",
    "Документы/описания": "Dokumente/Beschreibungen",
    "Авто: видеокарта, потом процессор": "Auto: GPU, dann CPU",
    "Только видеокарта": "Nur GPU",
    "Только процессор": "Nur CPU",
    "Авто": "Auto",
    "Безлимитно": "Unbegrenzt",
    "1 загрузка": "1 Download",
    "2 загрузки": "2 Downloads",
    "3 загрузки": "3 Downloads",
    "4 загрузки": "4 Downloads",
    "5 загрузки": "5 Downloads",
    "6 загрузки": "6 Downloads",
    "7 загрузки": "7 Downloads",
    "8 загрузки": "8 Downloads",
    "9 загрузки": "9 Downloads",
    "10 загрузки": "10 Downloads",
    "(не использовать)": "(nicht verwenden)",
    "необязательно": "optional",
    "Папка для загрузки": "Download-Ordner",
    "Путь к файлу доступа, если нужен ручной режим": "Pfad zur Zugriffsdatei für den manuellen Modus",
    "Автоматически раскладывать загрузки по сервисам и типам": "Downloads automatisch nach Dienst und Typ sortieren",
    "Переходить в фоновый режим при закрытии окна": "Beim Schließen in den Hintergrund wechseln",
    "Открывать приложение при запуске Windows": "App beim Windows-Start öffnen",
    "Автоматически проверять обновления приложения": "App-Updates automatisch prüfen",
    "Автоматически загружать обновления": "Updates automatisch herunterladen",
    "Устанавливать бета-версии": "Beta-Versionen installieren",
    "Автоматически менять кодек после скачивания, если выбран не оригинал": "Codec nach dem Download automatisch ändern, wenn nicht Original gewählt ist",
    "Спрашивать перед сменой кодека": "Vor Codec-Änderung nachfragen",
    "Сохранять оригиналы после конвертации": "Originale nach der Konvertierung behalten",
    "Показывать AV1 и VP9": "AV1 und VP9 anzeigen",
    "Плейлисты, каналы и результаты поиска": "Playlists, Kanäle und Suchergebnisse",
    "Создавать подпапки для плейлистов, каналов и результатов поиска": "Unterordner für Playlists, Kanäle und Suchergebnisse erstellen",
    "Нумеровать файлы": "Dateien nummerieren",
    "Пропускать уже скачанные элементы": "Bereits heruntergeladene Elemente überspringen",
    "Создавать файл .m3u": ".m3u-Datei erstellen",
    "Встраивать субтитры, если доступны": "Untertitel einbetten, wenn verfügbar",
    "Удалять завершённые элементы из списка": "Abgeschlossene Elemente aus der Liste entfernen",
    "Защита от одинаковых названий файлов": "Schutz vor doppelten Dateinamen",
    "Предлагать скачать канал после нескольких видео с него": "Nach mehreren Videos Kanal-Download vorschlagen",
    "Использовать прокси": "Proxy verwenden",
    "Предотвращать сон до завершения загрузок": "Ruhezustand verhindern, bis Downloads abgeschlossen sind",
    "Показывать уведомление о завершении загрузки": "Benachrichtigung nach Download anzeigen",
    "Показывать уведомление о завершении обработки": "Benachrichtigung nach Verarbeitung anzeigen",
    "Напоминать скачать новый контент": "An neue Inhalte erinnern",
    "Показывать похожие видео и рекомендации": "Ähnliche Videos und Empfehlungen anzeigen",
    "Запрашивать подтверждение при активных загрузках": "Bei aktiven Downloads Bestätigung anfordern",
    "Показывать в центре уведомлений": "Im Benachrichtigungscenter anzeigen",
    "Проигрывать звук оповещений": "Benachrichtigungston abspielen",
    "Автоматически обновлять доступ, когда сайт требует вход": "Zugriff automatisch aktualisieren, wenn Anmeldung erforderlich ist",
    "Отправлять статистику скачиваний": "Download-Statistiken senden",
    "Показывать инструменты обработки": "Verarbeitungswerkzeuge anzeigen",
    "Автоматически проверять обновления системы загрузки": "Updates des Download-Systems automatisch prüfen",
    "Логи": "Protokolle",
    "Файлы": "Dateien",
    "Эксперименты": "Experimente",
    "Support-пакет": "Support-Paket",
    "Готов к загрузке": "Bereit zum Herunterladen", "Загрузка": "Downloads", "Настройки": "Einstellungen", "История": "Verlauf", "Аккаунты": "Konten", "Исправления": "Korrekturen",
    "Загрузка видео, музыки и плейлистов": "Videos, Musik und Playlists herunterladen", "Вставить ссылку": "Link einfügen", "Скачать": "Herunterladen", "Проверить": "Prüfen",
    "Сохранить": "Speichern", "Основные": "Allgemein", "Соединение": "Verbindung", "Уведомления": "Benachrichtigungen", "Разработчик": "Entwickler",
    "Очередь загрузок": "Download-Warteschlange", "Дата": "Datum", "Источник": "Quelle", "Название": "Titel", "Размер": "Größe", "Прогресс": "Fortschritt", "Действия": "Aktionen",
    "Ожидание": "Warten", "Получение информации...": "Informationen werden gelesen...", "Загрузка...": "Wird heruntergeladen...", "Обработка...": "Wird verarbeitet...",
    "Конвертация...": "Wird konvertiert...", "Пауза": "Pausiert", "Завершено": "Abgeschlossen", "Отменено": "Abgebrochen", "Ошибка": "Fehler", "Проверено": "Geprüft",
    "Войти": "Anmelden", "Выйти": "Abmelden", "Версия 0.1.1 · дата фикса: 2026-07-28": "Version 0.1.1 · Korrekturdatum: 2026-07-28",
    "Критично": "Kritisch", "Серьёзно": "Wichtig", "Средне": "Mittel",
}


IT = EN | {
    "Настройки сохранены": "Impostazioni salvate",
    "Люкс графит": "Lux grafite",
    "Люкс ночная": "Lux notte",
    "Люкс светлая": "Lux chiara",
    "Лучшее": "Migliore",
    "Оригинал": "Originale",
    "h264 (рекомендуется)": "H.264 (consigliato)",
    "Видео": "Video",
    "Только аудио": "Solo audio",
    "Картинки/миниатюры": "Immagini/miniature",
    "Документы/описания": "Documenti/descrizioni",
    "Авто: видеокарта, потом процессор": "Auto: GPU, poi CPU",
    "Только видеокарта": "Solo GPU",
    "Только процессор": "Solo CPU",
    "Авто": "Auto",
    "Безлимитно": "Illimitato",
    "1 загрузка": "1 download",
    "2 загрузки": "2 download",
    "3 загрузки": "3 download",
    "4 загрузки": "4 download",
    "5 загрузки": "5 download",
    "6 загрузки": "6 download",
    "7 загрузки": "7 download",
    "8 загрузки": "8 download",
    "9 загрузки": "9 download",
    "10 загрузки": "10 download",
    "(не использовать)": "(non usare)",
    "необязательно": "opzionale",
    "Папка для загрузки": "Cartella download",
    "Путь к файлу доступа, если нужен ручной режим": "Percorso del file di accesso per la modalità manuale",
    "Автоматически раскладывать загрузки по сервисам и типам": "Organizza automaticamente i download per servizio e tipo",
    "Переходить в фоновый режим при закрытии окна": "Passa in background alla chiusura della finestra",
    "Открывать приложение при запуске Windows": "Apri l'app all'avvio di Windows",
    "Автоматически проверять обновления приложения": "Controlla automaticamente gli aggiornamenti dell'app",
    "Автоматически загружать обновления": "Scarica automaticamente gli aggiornamenti",
    "Устанавливать бета-версии": "Installa versioni beta",
    "Автоматически менять кодек после скачивания, если выбран не оригинал": "Cambia automaticamente codec dopo il download se non è selezionato Originale",
    "Спрашивать перед сменой кодека": "Chiedi prima di cambiare codec",
    "Сохранять оригиналы после конвертации": "Mantieni originali dopo la conversione",
    "Показывать AV1 и VP9": "Mostra AV1 e VP9",
    "Плейлисты, каналы и результаты поиска": "Playlist, canali e risultati di ricerca",
    "Создавать подпапки для плейлистов, каналов и результатов поиска": "Crea sottocartelle per playlist, canali e risultati di ricerca",
    "Нумеровать файлы": "Numera i file",
    "Пропускать уже скачанные элементы": "Salta elementi già scaricati",
    "Создавать файл .m3u": "Crea file .m3u",
    "Встраивать субтитры, если доступны": "Incorpora sottotitoli se disponibili",
    "Удалять завершённые элементы из списка": "Rimuovi elementi completati dall'elenco",
    "Защита от одинаковых названий файлов": "Protezione da nomi file duplicati",
    "Предлагать скачать канал после нескольких видео с него": "Suggerisci il download del canale dopo alcuni video",
    "Использовать прокси": "Usa proxy",
    "Предотвращать сон до завершения загрузок": "Impedisci sospensione fino al termine dei download",
    "Показывать уведомление о завершении загрузки": "Mostra notifica al termine del download",
    "Показывать уведомление о завершении обработки": "Mostra notifica al termine dell'elaborazione",
    "Напоминать скачать новый контент": "Ricorda di scaricare nuovi contenuti",
    "Показывать похожие видео и рекомендации": "Mostra video simili e consigli",
    "Запрашивать подтверждение при активных загрузках": "Chiedi conferma con download attivi",
    "Показывать в центре уведомлений": "Mostra nel centro notifiche",
    "Проигрывать звук оповещений": "Riproduci suono notifiche",
    "Автоматически обновлять доступ, когда сайт требует вход": "Aggiorna automaticamente l'accesso quando un sito richiede login",
    "Отправлять статистику скачиваний": "Invia statistiche download",
    "Показывать инструменты обработки": "Mostra strumenti di elaborazione",
    "Автоматически проверять обновления системы загрузки": "Controlla automaticamente aggiornamenti del sistema download",
    "Логи": "Log",
    "Файлы": "File",
    "Эксперименты": "Esperimenti",
    "Support-пакет": "Pacchetto supporto",
    "Готов к загрузке": "Pronto per il download", "Загрузка": "Download", "Настройки": "Impostazioni", "История": "Cronologia", "Аккаунты": "Account", "Исправления": "Correzioni",
    "Загрузка видео, музыки и плейлистов": "Scarica video, musica e playlist", "Вставить ссылку": "Incolla link", "Скачать": "Scarica", "Проверить": "Controlla",
    "Сохранить": "Salva", "Основные": "Generale", "Соединение": "Connessione", "Уведомления": "Notifiche", "Разработчик": "Sviluppatore",
    "Очередь загрузок": "Coda download", "Дата": "Data", "Источник": "Fonte", "Название": "Titolo", "Размер": "Dimensione", "Прогресс": "Avanzamento", "Действия": "Azioni",
    "Ожидание": "In attesa", "Получение информации...": "Lettura informazioni...", "Загрузка...": "Download in corso...", "Обработка...": "Elaborazione...",
    "Конвертация...": "Conversione...", "Пауза": "In pausa", "Завершено": "Completato", "Отменено": "Annullato", "Ошибка": "Errore", "Проверено": "Controllato",
    "Войти": "Accedi", "Выйти": "Esci", "Версия 0.1.1 · дата фикса: 2026-07-28": "Versione 0.1.1 · data correzione: 2026-07-28",
    "Критично": "Critico", "Серьёзно": "Importante", "Средне": "Medio",
}


TRANSLATIONS = {"ru": {}, "en": EN, "de": DE, "it": IT}


def _source_text(text: str) -> str:
    if not text:
        return text
    for mapping in TRANSLATIONS.values():
        for source, translated in mapping.items():
            if text == translated:
                return source
    return text


def translate(text: str, language: str) -> str:
    source = _source_text(text)
    return TRANSLATIONS.get(language, EN).get(source, source)


def apply_translations(root, language: str) -> None:
    language = language if language in TRANSLATIONS else "en"
    for label in root.findChildren(QLabel):
        label.setText(translate(label.text(), language))
    for button in root.findChildren(QAbstractButton):
        button.setText(translate(button.text(), language))
        button.setToolTip(translate(button.toolTip(), language))
    for group in root.findChildren(QGroupBox):
        group.setTitle(translate(group.title(), language))
    for edit in root.findChildren(QLineEdit):
        edit.setPlaceholderText(translate(edit.placeholderText(), language))
    for tabs in root.findChildren(QTabWidget):
        for index in range(tabs.count()):
            tabs.setTabText(index, translate(tabs.tabText(index), language))
    for combo in root.findChildren(QComboBox):
        for index in range(combo.count()):
            combo.setItemText(index, translate(combo.itemText(index), language))
    for table in root.findChildren(QTableWidget):
        for index in range(table.columnCount()):
            item = table.horizontalHeaderItem(index)
            if item:
                item.setText(translate(item.text(), language))
